# Site settings
title: 
description: > # this means to ignore newlines until "baseurl:"
  A blog about Linux and open source software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cornellio.net" # the base hostname & protocol for your site
twitter_username: 9dreamer
github_username:  cornellio

# Build settings
markdown: kramdown
